feat: add artist section
Solvro/web-juwenalia pull request #12
Opened 2024-11-23 22:38 UTC by jedryczkatymon

zrobiłem sekcję artystów i podpiąłem ją pod navbar
wyświetla ona wszystkie dane z naszego API i do czasu, aż UX/UI nie zostanie dowiezione to chyba tyle co mogę zrobić
(gdzieniegdzie przez przypadek również parę plików zformatowałem)

2024-11-26 11:57 UTC, Octopus4344 requested changes
Kod wyglada w wiekszosci ok, trzeba wprowadzic te kilka zmian, o ktorych pisalam

2024-11-26 11:57 UTC, Octopus4344 commented on src/components/ArtistList.tsx
Lepiej żeby artysta jako kafelek był osobnym komponentem w tej liście. Bedzie klikalny (url z cmsa nie wyswietlaj jako czesc opisu, jest po to zeby stworzyc przekierowanie po kliknieciu w artyste - mozesz dodac poki co przycisk zobacz wiecej przykladowo, albo caly kafelek klikalny).

2024-11-26 11:57 UTC, Octopus4344 commented on src/components/ArtistList.tsx
> +          />
To ci sie nie zrobi w kwadracie o tych wymiarach, musisz dodac takie klasy tailwindowe
```suggestion
          className={'aspect-square object-cover'}
          />
```

2024-11-26 12:33 UTC, jedryczkatymon reviewed
naprawiłem link razem ze zdjęciami artystów

2024-11-26 13:26 UTC, Octopus4344 reviewed
Zrob i rebasea i ta mala zmiane w next.config.ts mozesz wprowadzic i bede mogla mergowac :) 
Edit: jak ci rebase sie nie uda daj znac

2024-11-26 13:26 UTC, Octopus4344 commented on next.config.ts
> +  },
Tu lepiej tak: 
```suggestion
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cms.juwenalia.solvro.pl",
        port: "",
        pathname: "/assets/**",
      },
    ],
  },
```

2024-11-26 14:50 UTC, jedryczkatymon commented
tii chyba wyszło 10 commitów i 1h walki z merge conflictami później

2024-11-26 15:22 UTC, Octopus4344 approved these changes
Wiecej bledow nie widze poki co 🥇

2024-11-26 18:07 UTC, jedryczkatymon commented
oki supi czyli teraz czekamy do jutra na designy i poprawiamy tak jak na mockupach?

2024-12-02 15:46 UTC, zeolsem commented
@Octopus4344 myślę, że to, co ma być do środy to jest gotowe:
-podział artystów na popular i resztę (również random shuffle jako moja inwencja, nie wiem czy to chcemy),
-wizualny feedback przycisków na hover i active (odpowiednio najechanie myszą i kliknięcie),
-podane w Artist card krótko, gdzie i kiedy występuje artysta.

Jeżeli chodzi o przycisk 'Zobacz w harmonogramie' to nie wiem, jak dokładnie miałby działać. Jeżeli w harmonogramie byłyby zakładki (jako # w URL) to możnaby skoczyć do miejsca, gdzie jest konkretny artysta. Możnaby też dodać jakiś highlight artysty po przejściu na stronę harmonogram, ale to chyba bardziej na za rok (chyba że ktoś bardzo będzie chciał).

2024-12-07 00:05 UTC, Octopus4344 submitted a review, later dismissed
lgtm

2024-12-07 00:27 UTC, Octopus4344 approved these changes

2024-12-07 00:27 UTC, merged