Feat/artist component
Solvro/web-juwenalia pull request #39
Opened 2024-12-14 17:44 UTC by zeolsem

-Added animated sidebar navigating to organiser's social media
-Refactored Artist component and ArtistGrid

2024-12-15 00:51 UTC, Octopus4344 requested changes
Cos nie do konca chodzi z ta animacja

2024-12-15 00:51 UTC, Octopus4344 commented on src/components/Artist.tsx
> +  };
Po co używasz zmockowanych danych?

2024-12-15 00:51 UTC, Octopus4344 commented on src/components/ArtistList.tsx
> +            Nie udało nam się znaleźć podanych artystów. Wróć tutaj później!
Możesz użyć tego komponentu który zrobił Tymon w tym miejscu już

2024-12-15 00:51 UTC, Octopus4344 commented on src/sidebar/SocialsSidebar.tsx
> +  const tt_url = "https://www.youtube.com/watch?v=9bZkp7q19f0";
😭😭😭

2024-12-15 00:51 UTC, Octopus4344 commented on src/components/Artist.tsx
> +                // src={`/buttons/spotify-svgrepo-com.svg`} svg, but it's skeeweed
U mnie normalnie wyglada w sumie

2024-12-15 00:51 UTC, Octopus4344 commented on src/app/layout.tsx
>          <body>
zeby fixed dzialalo
```suggestion
        <body className = "relative">
```

2024-12-15 00:51 UTC, Octopus4344 commented on src/sidebar/SocialsSidebar.tsx
> +// export default SocialSidebar;
?

2024-12-15 00:51 UTC, Octopus4344 commented on src/sidebar/SocialsSidebar.tsx
Ogolnie tlo jest niewidoczne?

2024-12-16 08:23 UTC, Rei-x commented
@zeolsem 

https://docs.solvro.pl/guides/github/#nazewnictwo-commit%C3%B3w

2025-01-10 16:24 UTC, Octopus4344 requested changes

2025-01-10 16:24 UTC, Octopus4344 commented on src/components/artist-list.tsx
> +      <div className="mx-8 px-12">
```suggestion
      <PaddingWrapper className="">
```

2025-01-10 16:24 UTC, Octopus4344 commented on src/components/artist-list.tsx
> +      <div className="mx-auto mt-8 px-8">
```suggestion
      <PaddingWrapper className="mt-8">
```

2025-01-10 16:24 UTC, Octopus4344 commented on src/components/artist.tsx
> +              className="mx-2 flex w-full justify-between text-sm lg:text-xl"
Dodalabym tutaj jeszcze jeden breakpoint 
```suggestion
              className="mx-2 flex w-full justify-between text-sm lg:text-l xl:text-xl"
```

2025-01-10 16:24 UTC, Octopus4344 commented on src/components/artist.tsx
> +        <h2 className={"p-2 text-2xl font-extrabold lg:text-3xl"}>
```suggestion
        <h2 className={"p-2 text-2xl font-extrabold xl:text-3xl text-left"}>
```

2025-01-10 16:24 UTC, Octopus4344 commented on src/components/artist.tsx
> +                <div>
```suggestion
              <div className="text-left">{event.events_id.location.name.toUpperCase()}</div>

              {firstValidDay instanceof Date && (
                <div className="text-right">
```

2025-01-10 16:24 UTC, Octopus4344 commented on src/components/artist.tsx
> +      />
```suggestion
      <Image
        className={"mb-4 aspect-square rounded-xl object-cover h-[400px] sm:h-[621px] w-full"}
        src={`${API_URL}/assets/${image}`}
        alt={`Zdjęcie artysty ${name}`}
        width={441}
        height={621}
      />
```

2025-01-10 19:11 UTC, zeolsem commented on src/components/artist-list.tsx
makes sense

2025-01-15 07:15 UTC, merged