homepage sections for partners, organisers, creators
Solvro/web-juwenalia pull request #46
Opened 2024-12-18 02:04 UTC by kguzek

- [x] sekcja w homepage'u i mobile layout
- [x] fejkowe dane od copilota
- [x] medium & large layout
- [x] ogólny reusable component do ładnie podkreślanych elementów (linków itp.)
- [x] fixy związane z stylizacją i responsywnością
- [x] fix dla "brak tytułu" w facebook postach (również w pull #38)
- [ ] jakieś dynamiczne dane, ściąganie z CMSa? nie wiem co tam bedzie
- [ ] zdjęcia twórców

[resolves #27]

2024-12-18 03:22 UTC, kguzek commented
> * Dynamically generating class names for Tailwind CSS might not work as expected. Consider using a fixed class name or a different approach for dynamic colors.

Akurat ten komentarz co suppressed ma troche racji, ale o ile nikt nie będzie podawał za `color` kolorów nieużytych nigdzie indziej w aplikacji to nie powinno to być problemem.

2024-12-18 21:53 UTC, Octopus4344 requested changes
Bardzo fajnie wyglada tylko pare zmian zwiazanych z sama koncepcja trzeba wprowadzic

2024-12-18 21:53 UTC, Octopus4344 commented on src/lib/types.ts
> +}
tu jeszcze bedzie logo i nazwy w ogole nie wyswietlamy, możemy jej za to użyć jako alt
```suggestion

// #region --- About Us Page ---
export interface Organisation {
  name: string;
  url: string;
  logo: string;
}
```

2024-12-18 21:53 UTC, Octopus4344 commented on src/lib/types.ts
> +}
Jak tu na przyklad
<img width="1112" alt="Zrzut ekranu 2024-12-18 o 22 16 45" src="https://github.com/user-attachments/assets/31965b18-b10b-4f93-b794-6dc00de2e8a0" />

2024-12-18 21:53 UTC, Octopus4344 commented on src/components/homepage-header.tsx
Dogotowane widze

2024-12-18 21:53 UTC, Octopus4344 commented on src/components/about-us/creators.tsx
Wygląda pięknie, ale tego nie będzie na stronce, tylko te rzeczy które są w homepage na figmie, cala ta czesc o nas jest tam oznaczona jako nieaktywna, więc nią się nie sugeruj

2024-12-18 21:53 UTC, Octopus4344 commented on src/components/navbar.tsx
> +      <Link href="/postsFb">Aktualności</Link>
Tu coś poszło nie tak
```suggestion
      <Link href="/posts-fb">Aktualności</Link>
```

2024-12-18 21:53 UTC, Octopus4344 commented on src/components/about-us/organisers.tsx
> +    { name: "Konrad Guzek", role: "Lider projektu" },
XDDD nice

2024-12-19 16:00 UTC, kguzek commented on src/components/navbar.tsx
> +      <Link href="/postsFb">Aktualności</Link>
w tym drugim branchu i tak zmieniłem na `/news`, więc się zmieni tak czy siak

2024-12-19 21:58 UTC, Octopus4344 approved these changes

2024-12-19 21:58 UTC, merged