feat: add generic carousel component
Solvro/web-juwenalia pull request #57
Opened 2024-12-23 19:54 UTC by jedryczkatymon

dodałem komponent karuzeli, który na razie na potrzeby review ma jeszcze kilka zhardokowanych elementów z bordową obwódką, żeby można było odróżnić poszególne elementy

2024-12-27 19:20 UTC, Octopus4344 requested changes

2024-12-27 19:20 UTC, Octopus4344 commented on src/components/generic-carousel-component.tsx
Wygląda ładnie, z tym ze dla wiekszej liczby elementow sie psuje, z mniejszych problemow, trzeba zwiekszyc odleglosci miedzy elementami i border radius
<img width="259" alt="Zrzut ekranu 2024-12-27 o 20 17 48" src="https://github.com/user-attachments/assets/34db27b7-68f9-4fc8-823b-b90310451849" />

2024-12-27 20:24 UTC, jedryczkatymon commented on src/components/generic-carousel-component.tsx
przyjąłem 🫡

2025-01-07 11:52 UTC, Octopus4344 commented
Karuzele omówimy w trójkę z Adrianem w czwartek na spotkaniu

2025-01-23 19:55 UTC, Octopus4344 requested changes
Poza tym jednym wszystko git ode mnie

2025-01-23 19:55 UTC, Octopus4344 commented on src/lib/types.ts
> +
To tutaj bez sensu, w ogóle nie ma potrzeby definiowania osobnego typu (Z JEDNA LISTA), zrob jako inline w karuzeli

2025-01-24 09:18 UTC, jedryczkatymon commented on src/lib/types.ts
> +
spokojnie wiem że bez sensu to było ale jak robiłem inaczej to się wywalało teraz przysiadłem nad tym trochę i się tego pozbyłem

2025-01-24 14:07 UTC, Octopus4344 commented
![image](https://github.com/user-attachments/assets/32d8a83f-22ee-4845-84b4-8fb87524fc63)
😠😠😠

2025-01-24 14:08 UTC, Octopus4344 approved these changes

2025-01-24 15:08 UTC, jedryczkatymon commented
> ![image](https://private-user-images.githubusercontent.com/156484850/406465182-32d8a83f-22ee-4845-84b4-8fb87524fc63.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3MzEzNzIsIm5iZiI6MTczNzczMTA3MiwicGF0aCI6Ii8xNTY0ODQ4NTAvNDA2NDY1MTgyLTMyZDhhODNmLTIyZWUtNDg0NS04NGI0LThmYjg3NTI0ZmM2My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjRUMTUwNDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUyZTg0YWI0YjcxYTc4ZWM1OTRlY2FlZDM4NDE5M2RjNWM1ZDQ4ZjcxOTI2OTZlYmJmYTczN2FkNDU3ZTIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ge8uEMEeyT9FcNpXkwSEXSyIckA8JnSNrTq1opXo6mk) 😠😠😠 Tak proszę nie robić

hmm dziwne musiałem coś w vscode klinkąć chyba bo nic takiego w terminalu nie robiłem

2025-01-25 21:13 UTC, kguzek requested changes

2025-01-25 21:13 UTC, kguzek commented on src/lib/facebook.ts
> +      .filter((post) => Boolean(post.message))
Imo lepiej jest używać `!!` [niż Boolean](https://airbnb.io/javascript/#coercion--booleans)

W tym przypadku jeśli chcesz być bardziej explicit to mógłbyś nawet tak zrobić:

```suggestion
      .filter((post) => post.message != null && post.message.length > 0)
```

2025-01-25 21:13 UTC, kguzek commented on src/components/artists-carousel.tsx
> +  const artists_raw = response.data;
nie używamy `snake_case` w TypeScripcie!

```suggestion
```

2025-01-25 21:13 UTC, kguzek commented on src/components/artists-carousel.tsx
> +  const artists = [...popularArtists];
Usunąłbym to, bo to zużywa tylko więcej pamięci jak kopiujesz array

```suggestion
```

2025-01-25 21:13 UTC, kguzek commented on src/components/artists-carousel.tsx
> +  const popularArtists = artists_raw.filter((artist) => artist.isPopular);
w tym przypadku jak tylko raz użwyasz to nie ma sensu raczej tworzyć tego `artists_raw` (jak już to `artistsRaw`)

```suggestion
  const popularArtists = response.data.filter((artist) => artist.isPopular);
```

2025-01-25 21:13 UTC, kguzek commented on src/components/artists-carousel.tsx
> +  return <Carousel artists={artists} />;
potem tu użyj bezpośrednio `popularArtists`
```suggestion
  return <Carousel artists={popularArtists} />;
```

2025-01-28 08:51 UTC, Octopus4344 requested changes

2025-01-28 08:51 UTC, Octopus4344 commented on src/components/artists-carousel.tsx
Komponent jest niepełny, nie ma headera i odnośnika zobacz więcej, w związku z tym dodaj też obsługę pustej listy - nie będzie błedu ale będzie pusty header. Wprowadz tez obsluge bledow dla pożądku.

2025-01-28 09:00 UTC, Octopus4344 commented
Opakuj tez w padding wrapper

2025-01-28 09:00 UTC, Octopus4344 commented
I moxzesz zmienic nazwe z generic na artist carousel, żeby nikogo nie mylilo :)

2025-02-07 11:56 UTC, closed without merging